[tool.poetry]
name = "django-startset"
version = "0.1.0"
description = "柿崎さんによる復習"
authors = ["Akito Harada"]

[tool.poetry.dependencies]
python = "^3.7"
Django = "^3.2.5"
djangorestframework-filters = "^0.11.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
